### ISSUE TITLE
Allow magic redirection filter to javascript

### ISSUE THREAD

**Issue by antononcube** [bduggan/raku-jupyter-kernel#100]
Please, implement in the magics specifications "filter redirection" from Raku to JavaScript -- `%% raku > javascript` and/or `%% perl6 > javascript`.

(This type of specification is already available for LaTeX <-> HTML.)

For example, with this kind of specification:

```
%%  raku > javasript
<raku-code-that-produces-javascript-d3-code>
```

I can produce the plot shown here:

![](https://i.imgur.com/Ka8PaiH.png)

------

Currently, I am using this very "targeted" hack to be able to make the JavaScript D3 diagrams as the one above:

```perl6
sub mime-type($str) is export {
    return do given $str {
        when /:i ^ '<svg' / {
            'image/svg+xml';
        }
        when /:i ^ '<img' / {
            'text/html';
        }
        when / ^ \s* '(function(element)' \s* '{' \s* 'require' \s* '(' \s* '[\'d3\']' \s* ',' \s* 'function(d3)'  \s* '{' / {
            'application/javascript';
        }
        default { 'text/plain' }
    }
}
```

------

*(This request related is to related to my [previous one](https://github.com/bduggan/p6-jupyter-kernel/issues/99#issue-1488526432), but as far as I can tell requires different implementation approach.)*

**Comment by antononcube** [comment]
> There is a #% javascript magic -- is that sufficient?

No, it is not -- I am proposing Raku code (in Raku cells) that generates JavaScript code to have the results of the JavaScript code in the corresponding output cell.

**Comment by antononcube** [comment]
Thank you!
Just tried it:

![](https://i.imgur.com/A18h6se.png)

(Using the package ["JavaScript::D3"](https://github.com/antononcube/Raku-JavaScript-D3).)

**Comment by bduggan** [comment]
cool!
