### ISSUE TITLE
Multi-dimensional array creation crashes the kernel

### ISSUE THREAD

**Issue by antononcube** [bduggan/raku-jupyter-kernel#101]
When I execute multi-dimensional (shaped) array creations I reliably get crashes.

The error / warning / exception messages include :

> Original exception:
>        Partially dimensioned views of shaped arrays not yet implemented. Sorry.

For example this evaluation:

```perl6
Array.new(:shape(10, 2), [1.7321434309227173e0, 6.2572469021756465e0], [9.932295929416135e0, 6.485818373046102e0], [7.225417902849154e0, 7.991374606871018e0], [3.7905362879868476e0, 0.08954289370900881e0], [5.880645287095184e0, 3.3552096949310735e0], [6.304702611189215e0, 1.5674934815689476e0], [3.0093399646665784e0, 1.0472011403621253e0], [2.6382288018622764e0, 4.152205738604334e0], [4.943829952204391e0, 1.9587886346847405e0], [10.732314541349194e0, 7.092417753717617e0])
```

Such crashes do not happen in Commaide's REPL.

I am not sure how important is this issue and should it be fixed in "Jupyter::Kernel".

**Comment by bduggan** [comment]
thanks!  Should be fixed now.
