### ISSUE TITLE
In jupyter-console only, warning about "not responding properly to is_complete_request" shows after every command.

### ISSUE THREAD

**Issue by ramillies** [bduggan/raku-jupyter-kernel#103]
Jupyter console with this kernel can be normally started and normally used. However, after submitting each command, the console spits out a lengthy warning. It's mostly a cosmetic problem -- everything works correctly, the warnings just clutter up the screen in an unpleasant manner.

A transcript of a typical session looks somewhat like this:

    Welcome to Rakudo™ v2022.07.
    Implementing the Raku® Programming Language v6.d.
    Built on MoarVM version 2022.07.
    
    Jupyter console 6.4.4
    
    Welcome to Raku 🦋 (rakudo 2022.07).
    In [1]: my @a = 1,2,3/usr/lib/python3/dist-packages/jupyter_console/ptshell.py:793: UserWarning: The kernel did not respond properly to an is_complete_request: {'header': {'msg_type': 'history_reply', 'version': '5.3', 'username': 'kernel', 'msg_id': 'a23d379c-45f2-41c3-8d50-390f8c41edcf', 'date': datetime.datetime(2023, 3, 29, 13, 8, 43, 544387, tzinfo=tzutc()), 'session': 'dee67e49-6db4-4509-97d2-f8ee096778be'}, 'msg_id': 'a23d379c-45f2-41c3-8d50-390f8c41edcf', 'msg_type': 'history_reply', 'parent_header': {'version': '5.3', 'date': datetime.datetime(2023, 3, 29, 13, 8, 42, 880877, tzinfo=tzutc()), 'msg_id': '5b7df9f1-041672fbf2dc8ca4df21eaa5_145148_1', 'msg_type': 'history_request', 'session': '5b7df9f1-041672fbf2dc8ca4df21eaa5', 'username': 'glorfindel'}, 'metadata': {}, 'content': {'history': [[1, 1, 'my @a = [ 1, 2, 3 ]'], [1, 2, '@a.push(4)'], [1, 3, '@a'], [2, 1, '(1..10000).map({ (2*$_+3)/$_**2/($_+1)**2/($_+2)**2/($_+3)**2 }).sum'], (...), [117, 1, '1+1']]}, 'buffers': []}.
      warn('The kernel did not respond properly to an is_complete_request: %s.' % str(msg))
    In [1]: my @a = 1,2,3
    Out[1]: [1 2 3]
    
    In [1]: @a.sum/@a/usr/lib/python3/dist-packages/jupyter_console/ptshell.py:793: UserWarning: The kernel did not respond properly to an is_complete_request: {'header': {'username': 'kernel', 'date': datetime.datetime(2023, 3, 29, 13, 8, 51, 873836, tzinfo=tzutc()), 'session': 'dee67e49-6db4-4509-97d2-f8ee096778be', 'msg_type': 'execute_reply', 'version': '5.3', 'msg_id': 'f7321245-7120-4080-bae1-fcab8e3864a2'}, 'msg_id': 'f7321245-7120-4080-bae1-fcab8e3864a2', 'msg_type': 'execute_reply', 'parent_header': {'version': '5.3', 'date': datetime.datetime(2023, 3, 29, 13, 8, 51, 721018, tzinfo=tzutc()), 'msg_type': 'execute_request', 'msg_id': '5b7df9f1-041672fbf2dc8ca4df21eaa5_145148_3', 'session': '5b7df9f1-041672fbf2dc8ca4df21eaa5', 'username': 'glorfindel'}, 'metadata': {'dependencies_met': True, 'engine': '919c0b0b-c95c-4298-8ffc-f73d548b9cab', 'status': 'ok', 'started': '2023-03-29T13:08:51.872889Z'}, 'content': {'execution_count': 1, 'user_expressions': {}, 'status': 'ok', 'payload': []}, 'buffers': []}.
      warn('The kernel did not respond properly to an is_complete_request: %s.' % str(msg))
    In [1]: @a.sum/@a
    Out[2]: 2
    
    In [2]: "Hello! The average of {@a.fmt("%s", ", ")} is {@a.sum/@a}./usr/lib/python3/dist-packages/jupyter_console/ptshell.py:793: UserWarning: The kernel did not respond properly to an is_complete_request: {'header': {'username': 'kernel', 'version': '5.3', 'msg_type': 'execute_reply', 'date': datetime.datetime(2023, 3, 29, 13, 10, 4, 674546, tzinfo=tzutc()), 'session': 'dee67e49-6db4-4509-97d2-f8ee096778be', 'msg_id': 'd4eae0b2-5589-4167-998c-a108c26c64b0'}, 'msg_id': 'd4eae0b2-5589-4167-998c-a108c26c64b0', 'msg_type': 'execute_reply', 'parent_header': {'session': '5b7df9f1-041672fbf2dc8ca4df21eaa5', 'username': 'glorfindel', 'msg_id': '5b7df9f1-041672fbf2dc8ca4df21eaa5_145148_11', 'date': datetime.datetime(2023, 3, 29, 13, 10, 4, 544999, tzinfo=tzutc()), 'version': '5.3', 'msg_type': 'execute_request'}, 'metadata': {'status': 'ok', 'dependencies_met': True, 'started': '2023-03-29T13:10:04.673760Z', 'engine': '919c0b0b-c95c-4298-8ffc-f73d548b9cab'}, 'content': {'user_expressions': {}, 'status': 'ok', 'execution_count': 5, 'payload': []}, 'buffers': []}.
      warn('The kernel did not respond properly to an is_complete_request: %s.' % str(msg))
    In [2]: "Hello! The average of {@a.fmt("%s", ", ")} is {@a.sum/@a}."
    Out[3]: Hello! The average of 1, 2, 3 is 2.

After the first command, the warning is especially long, because it apparently lists everything I have ever typed into the console using this kernel. I skipped most of it with `(...)` in the listing above.

All in all, the problem of warnings cluttering the screen can be solved just by redirecting STDERR to `/dev/null`, but perhaps the warnings indicate some deeper problem.

I'm on Debian bookworm/sid, Jupyter console 6.4.4, raku 2022.07, Jupyter::Kernel v0.0.20, with default Jupyter configuration, except for the "is_complete_request timeout" and color schemes being set differently.

Not sure if it makes any difference, but here are the versions of various Jupyter packages:

    Selected Jupyter core packages...
    IPython          : 8.5.0
    ipykernel        : 6.17.0
    ipywidgets       : 6.0.0
    jupyter_client   : 7.4.9
    jupyter_core     : 4.12.0
    jupyter_server   : not installed
    jupyterlab       : not installed
    nbclient         : 0.7.2
    nbconvert        : 6.5.3
    nbformat         : 5.5.0
    notebook         : 6.4.12
    qtconsole        : not installed
    traitlets        : 5.5.0

If you need any other info, I will happily provide it. I also understand it's not much of an issue, but still it's moderately annoying, and as such it would probably better if the warnings didn't occur.

**Comment by bduggan** [comment]
Hi @ramillies,

Can you try upgrading to version 0.0.21?  This sounds like the same issue as https://github.com/bduggan/raku-jupyter-kernel/issues/102

Brian

**Comment by ramillies** [comment]
Sorry if it's the same issue, it didn't look like it from the title. However, I've just upgraded to 0.0.21 and the warnings are still there.

**Comment by bduggan** [comment]
okay interesting.  Another possibility is the timeout setting, perhaps try increasing it with something like:
```
jupyter-console --debug --kernel=raku --ZMQTerminalInteractiveShell.kernel_is_complete_timeout=10.0
```

**Comment by bduggan** [comment]
Sorry, I didn't read your message carefully enough:
> I'm on Debian bookworm/sid, Jupyter console 6.4.4, raku 2022.07, Jupyter::Kernel v0.0.20, with default Jupyter configuration, except for the "is_complete_request timeout" and color schemes being set differently.

It does seems related to setting is_complete_request timeout -- what is it set to?
Also, if this interaction is occurring even without trying autocompletion, that would be odd.  Are there any clues in `jupyter.log`?

**Comment by bduggan** [comment]
Hmm, yes, the server log looks normal.  The errors in the original description are definitely a little odd, since it looks like other messages types -- history_reply, execute_reply -- are being treated as responses to an is_complete_request.  A workaround might be to disable autocompletion by changing the config value of `c.ZMQTerminalInteractiveShell.use_kernel_is_complete`

**Comment by ramillies** [comment]
If I set `c.ZMQTerminalInteractiveShell.use_kernel_is_complete = True`, it's not possible to submit any command. For instance, if I enter `1+1` and hit ENTER, Jupyter won't recognize that it should evaluate the command and instead prompts for a continuation with `...` indefinitely.

**Comment by bduggan** [comment]
Very strange!  Another question: does this happen with other kernels, or just the Raku kernel?

**Comment by ramillies** [comment]
It does happen with Python as well. However, I found that I have to hit ENTER three times instead of once. After the third ENTER the command is submitted... That is true for Raku as well as for the Python kernel.

**Comment by bduggan** [comment]
Okay, since this isn't specific to the Raku kernel, it sounds like I should go ahead and close this issue; perhaps it is specific to the setup, or an issue in the client.
