### ISSUE TITLE
Markdown magic

### ISSUE THREAD

**Issue by antononcube** [bduggan/raku-jupyter-kernel#104]
It would be very nice to have a Markdown magic. Then  we can specify cells that generate and insert content -- see the attached screenshots.

![Raku-Jupyter-Kernel-Markdown-magic-cells](https://github.com/bduggan/raku-jupyter-kernel/assets/4943081/e08fb1f8-63c9-478a-83af-55521debeb50)

------

The implementation is trivial with the current magics framework -- see this [Magics.rakumod](https://github.com/antononcube/Raku-Jupyter-Chatbook/commit/493df3ad915ef825cd94fb5d1e402f94dac35a9f) file.
(I was not sure should I make PR or not...)

**Comment by bduggan** [comment]
Hi Anton,

The implementation looks great.  Definitely feel free to make a PR, and I'll merge it.

Brian

**Comment by antononcube** [comment]
I did that earlier. Thanks!

**Comment by antononcube** [comment]
Completed -- see : https://github.com/bduggan/raku-jupyter-kernel/pull/105#issuecomment-1701050185 .
