### ISSUE TITLE
Keep input in $In array

### ISSUE THREAD

**Issue by antononcube** [bduggan/raku-jupyter-kernel#106]
I think it is natural a user to expect access to previous inputs, e.g. `In[3]` since access to previous outputs is available, e.g. `Out[3]`.

Paraphrasing  "keep output" description in the README as a "keep input" spec:

> **Keep input:** All cells are evaluated in item context. Inputs are then saved to an array named `$In`. 
> You can read from this directly or via the subroutine `In` (e.g. `In[3]`).

-----

This should be a "quick" implementation -- if I am not missing something -- see [here](https://github.com/antononcube/Raku-Jupyter-Chatbook/blob/9e47c501c22b1886300e657c4a0345fab0573674/lib/Jupyter/Kernel/Sandbox.rakumod#L79)  and [here](https://github.com/antononcube/Raku-Jupyter-Chatbook/blob/9e47c501c22b1886300e657c4a0345fab0573674/lib/Jupyter/Kernel/Sandbox.rakumod#L108).

**Comment by antononcube** [comment]
Ok, I will submit a PR. I have to figure out appropriate unit tests first.

My only "problem" is that this Raku code for adding the unevaluated input into `$In` might be too naive:

```perl6
                \$In[$store] := q:to/END99erx3ds00e0xxdreREIFer929eecw143/;
                $code
                END99erx3ds00e0xxdreREIFer929eecw143
```

-----

>  I wonder if some sort of analog to a shell command history would accompany this, like !3 to actually do the eval of In[3] [...]
 
Interesting idea!

One possible generalization is to have "service" or "meta" cells that give Raku-programmatic access to the underlying session data structures.

**Comment by bduggan** [comment]
The code to add to `$In` seems fine.

I think I'd need to seem some examples to understand the generalization you're describing.

**Comment by antononcube** [comment]
> The code to add to `$In` seems fine.

Ok. Thanks!


> I think I'd need to see some examples to understand the generalization you're describing.

Please see the section ["Chat meta cells"](https://github.com/antononcube/Raku-Jupyter-Chatbook#chat-meta-cells) of the README of ["Jupyter::Chatbook"](https://github.com/antononcube/Raku-Jupyter-Chatbook).

[The corresponding Jupyter notebook/chatbook](https://github.com/antononcube/Raku-Jupyter-Chatbook/blob/master/eg/Chatbook-LLM-chats.ipynb) has usage examples. (The last section.)

**Comment by bduggan** [comment]
What if the kernel provided the current cell number in a dynamic variable?  Then you could do something like
```
@meta[$*JUPYTER-CURRRENT-CELL] = ...
```

**Comment by antononcube** [comment]
Interesting idea! 

Can we have also the array variable `@*JUPYTER-CELLS` ?

----

I think my generalization proposal is still more general. With a meta-cell we can have for example:

- Programmatic access to all cells in the notebook (both inputs and outputs)
- Ability to specify pre- and post processing notebook-wide in one cell
   - The magic `always` provides that, but, say, `prepend` and `append` specs have to be put in different cells.
   - I think `always` is "sufficient" -- I am just trying to exemplify the meta-cell idea

BTW, I would not feel strongly about having meta-cells if `@*JUPYTER-CELLS` and `@meta[$*JUPYTER-CURRRENT-CELL] = ...` are implemented.

----
 
I would need something like accessing previous cell's input or output in order to have certain *chatbook* prompt-based functionalities completed.

**Comment by bduggan** [comment]
How is `@*JUPYTER-CELLS` different from `In` and `Out`?  Or is this just a different name?

If there is a `$*JUPYTER-CURRENT-CELL` then the previous cell's input would be in `In[$*JUPYTER-CURRENT-CELL - 1]` -- but I could see how looking at the top of an array is more convenient.

Another interesting thing this would allow would be to eval the AST from `In`, e.g.
```
In [1]: say "hello world"
hello world

In [2]: In[1]
Out[2]: say "hello world"

In [3]: In[1].AST
Out[3]:
RakuAST::StatementList.new(
  RakuAST::Statement::Expression.new(
    expression => RakuAST::Call::Name.new(
      name => RakuAST::Name.from-identifier("say"),
      args => RakuAST::ArgList.new(
        RakuAST::QuotedString.new(
          segments   => (
            RakuAST::StrLiteral.new("hello world"),
          )
        )
      )
    )
  )
)

In [4]: In[1].AST.EVAL
hello world
```

**Comment by antononcube** [comment]
> How is @*JUPYTER-CELLS different from In and Out? Or is this just a different name?

Well, there is no 1-to-1 correspondence between Jupyter cells and the different evaluations. One cell can be evaluated multiple times and its content (i.e. the input) can be changed every time. 

Another point is that the order of the cells does not correspond to the order of input evaluation history.

And, yes, the AST application is interesting!

**Comment by antononcube** [comment]
Right -- that is why I was/am thinking about using meta cells.

**Comment by bduggan** [comment]
Is there a simple magic that would help, like for instance a `%% tag` magic for adding key/value pairs associated with a cell?  Then if a cell is executed multiple times but has the same tag, all the outputs could be found by looking for the elements of `Out` whose indexes are found by looking for a particular tag value

**Comment by antononcube** [comment]
That would be nice. 

BTW, dthe JSON representation of the Jupyter notebook also keeps track of the number of evaluations. For example, here is a cell from [this notebook](https://github.com/antononcube/Raku-Jupyter-Chatbook/blob/master/eg/Chatbook-LLM-cells.ipynb):

```json
 {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\n",
       "\n",
       "Dog Names:\n",
       "1. Lady\n",
       "2. Duke\n",
       "3. Luna\n",
       "\n",
       "Cat Names:\n",
       "1. Fluffy\n",
       "2. Tiger\n",
       "3. Muffin\n",
       "4. Shadow"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#% openai\n",
    "Randomly generate 3 dog names and 4 cat names."
   ]
  }
```

**Comment by bduggan** [comment]
I've committed ca7666e2025c1919e1a4827c6029f58999a8a3e8 which resolves the original request, so I'll go ahead and close this issue -- we can treat the other potential changes in separate issues
