### ISSUE TITLE
Add Raku to Jupyter Wiki list of jupyter kernels.

### ISSUE THREAD

**Issue by bazzaar** [bduggan/raku-jupyter-kernel#108]
Ah, I see now the kernel is listed under Perl 6.C, should that entry be revised to Raku?

---

On the Jupyter Wiki ( https://github.com/jupyter/jupyter/wiki/Jupyter-kernels ) there's a community-compiled list of Jupyter kernels for different programming languages. Raku is absent from the list (I think, it's a long list).

**Comment by bduggan** [comment]
Done

https://github.com/jupyter/jupyter/wiki/Jupyter-kernels/_compare/bc2eb54d8ec48e38fa9ea81bfd4e4e387429800d
