### ISSUE TITLE
Cannot run REPL with moar-2024.12

### ISSUE THREAD

**Issue by antononcube** [bduggan/raku-jupyter-kernel#115]
After installing the new Raku distribution on macOS (moar-2024.12), installing "Jupyter::Kernel", and then running the command:

```
jupyter console --kernel=raku
```

produces the error message:

> Died with the exception:
>    Invalid REPL environment: Unable to initialize REPL outside of a TTY

See the related issues reported for "Jupyter::Chatbook" :  https://github.com/rakudo/rakudo/issues/5726 .

(I investigated and asked about possible fixes without success...)

**Comment by bduggan** [comment]
Thanks, I'm able to reproduce this on linux also.

**Comment by bduggan** [comment]
Here is a workaround, but probably there should be a mechanism in the raku core to allow non-tty use of the repl -> https://github.com/bduggan/raku-jupyter-kernel/pull/116

**Comment by bduggan** [comment]
I merged the PR,  so it'll be fixed in 1.0.3 (headed out now)

**Comment by antononcube** [comment]
Thanks a lot!
